// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'ProductLineDetailModel.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

ProductLineDetailModel _$ProductLineDetailModelFromJson(
    Map<String, dynamic> json) {
  return ProductLineDetailModel(
    json['CurrProductName'] as String,
    json['CurrStateName'] as String,
    json['ID'] as int,
    json['LineCode'] as String,
    json['LineName'] as String,
    json['CurrState'] as String,
    json['CurrStateDesc'] as int,
    json['PreState'] as String,
    json['PreStateDesc'] as int,
    json['Remark'] as String,
    json['ExceptionType'] as String,
    json['ExceptionWorkOrder'] as String,
    json['BADALARMType'] as String,
    json['BADALARMTypeDesc'] as int,
    json['BADALARMDate'] as String,
    json['CurrTime'] as String,
    json['PreTime'] as String,
    json['CurrProductCode'] as String,
    json['PreProductCode'] as String,
    json['FirstQCType'] as String,
    (json['LineOEE'] as num)?.toDouble(),
    (json['LineMobility'] as num)?.toDouble(),
    (json['LineYield'] as num)?.toDouble(),
    (json['LineExpressivity'] as num)?.toDouble(),
    json['ProductNo'] as String,
    json['PlanNumber'] as int,
    json['ActualNumber'] as int,
    (json['PassageRate'] as num)?.toDouble(),
    (json['DirectPassRate'] as num)?.toDouble(),
    (json['Progress'] as num)?.toDouble(),
    json['ReworkNumber'] as int,
    json['ScrapNumber'] as int,
    json['LockNumber'] as int,
    json['BadNumber'] as int,
    (json['LineYieldPlan'] as num)?.toDouble(),
    (json['ProgressPlan'] as num)?.toDouble(),
    json['Delflag'] as bool,
    json['CreateTime'] as String,
    json['Creator'] as String,
    json['ModifiedTime'] as String,
    json['Modifier'] as String,
    json['RowVersion'] as String,
  );
}

Map<String, dynamic> _$ProductLineDetailModelToJson(
        ProductLineDetailModel instance) =>
    <String, dynamic>{
      'CurrProductName': instance.CurrProductName,
      'CurrStateName': instance.CurrStateName,
      'ID': instance.ID,
      'LineCode': instance.LineCode,
      'LineName': instance.LineName,
      'CurrState': instance.CurrState,
      'CurrStateDesc': instance.CurrStateDesc,
      'PreState': instance.PreState,
      'PreStateDesc': instance.PreStateDesc,
      'Remark': instance.Remark,
      'ExceptionType': instance.ExceptionType,
      'ExceptionWorkOrder': instance.ExceptionWorkOrder,
      'BADALARMType': instance.BADALARMType,
      'BADALARMTypeDesc': instance.BADALARMTypeDesc,
      'BADALARMDate': instance.BADALARMDate,
      'CurrTime': instance.CurrTime,
      'PreTime': instance.PreTime,
      'CurrProductCode': instance.CurrProductCode,
      'PreProductCode': instance.PreProductCode,
      'FirstQCType': instance.FirstQCType,
      'LineOEE': instance.LineOEE,
      'LineMobility': instance.LineMobility,
      'LineYield': instance.LineYield,
      'LineExpressivity': instance.LineExpressivity,
      'ProductNo': instance.ProductNo,
      'PlanNumber': instance.PlanNumber,
      'ActualNumber': instance.ActualNumber,
      'PassageRate': instance.PassageRate,
      'DirectPassRate': instance.DirectPassRate,
      'Progress': instance.Progress,
      'ReworkNumber': instance.ReworkNumber,
      'ScrapNumber': instance.ScrapNumber,
      'LockNumber': instance.LockNumber,
      'BadNumber': instance.BadNumber,
      'LineYieldPlan': instance.LineYieldPlan,
      'ProgressPlan': instance.ProgressPlan,
      'Delflag': instance.Delflag,
      'CreateTime': instance.CreateTime,
      'Creator': instance.Creator,
      'ModifiedTime': instance.ModifiedTime,
      'Modifier': instance.Modifier,
      'RowVersion': instance.RowVersion,
    };
